#!/usr/bin/env node
/**
 * Verifies es/en i18n key parity and optionally normalizes JSON + generated types.
 *
 * Usage:
 *   node scripts/i18n-check.mjs              # parity check (default)
 *   node scripts/i18n-check.mjs --sort       # sort object keys recursively
 *   node scripts/i18n-check.mjs --types        # write i18n-keys.generated.ts
 *   node scripts/i18n-check.mjs --sort --types # normalize + regenerate types
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const ES_PATH = path.join(ROOT, 'src/assets/i18n/es.json');
const EN_PATH = path.join(ROOT, 'src/assets/i18n/en.json');
const TYPES_PATH = path.join(ROOT, 'src/app/core/i18n/i18n-keys.generated.ts');

function sortObjectDeep(value) {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    return value;
  }

  return Object.keys(value)
    .sort((a, b) => a.localeCompare(b))
    .reduce((sorted, key) => {
      sorted[key] = sortObjectDeep(value[key]);
      return sorted;
    }, {});
}

function flattenKeys(obj, prefix = '') {
  const keys = [];

  for (const key of Object.keys(obj).sort((a, b) => a.localeCompare(b))) {
    const fullKey = prefix ? `${prefix}.${key}` : key;
    const value = obj[key];

    if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
      keys.push(...flattenKeys(value, fullKey));
    } else {
      keys.push(fullKey);
    }
  }

  return keys;
}

function writeJson(filePath, data) {
  fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`, 'utf8');
}

function writeTypes(keys) {
  const header = `// Generated by scripts/i18n-check.mjs — do not edit manually.\n\n`;
  const array = keys.map((key) => `  '${key.replace(/'/g, "\\'")}',`).join('\n');
  const content = `${header}export const I18N_KEYS = [\n${array}\n] as const;\n\nexport type I18nKey = (typeof I18N_KEYS)[number];\n`;
  fs.mkdirSync(path.dirname(TYPES_PATH), { recursive: true });
  fs.writeFileSync(TYPES_PATH, content, 'utf8');
}

function main() {
  const shouldSort = process.argv.includes('--sort');
  const shouldWriteTypes = process.argv.includes('--types');

  let es = JSON.parse(fs.readFileSync(ES_PATH, 'utf8'));
  let en = JSON.parse(fs.readFileSync(EN_PATH, 'utf8'));

  if (shouldSort) {
    es = sortObjectDeep(es);
    en = sortObjectDeep(en);
    writeJson(ES_PATH, es);
    writeJson(EN_PATH, en);
    console.log('Sorted i18n files:', path.relative(ROOT, ES_PATH), path.relative(ROOT, EN_PATH));
  }

  const esKeys = flattenKeys(es);
  const enKeys = flattenKeys(en);
  const esSet = new Set(esKeys);
  const enSet = new Set(enKeys);

  const onlyEs = esKeys.filter((key) => !enSet.has(key));
  const onlyEn = enKeys.filter((key) => !esSet.has(key));

  if (onlyEs.length > 0 || onlyEn.length > 0) {
    console.error('i18n parity check failed.');
    if (onlyEs.length > 0) {
      console.error(`Missing in en.json (${onlyEs.length}):`);
      onlyEs.forEach((key) => console.error(`  - ${key}`));
    }
    if (onlyEn.length > 0) {
      console.error(`Missing in es.json (${onlyEn.length}):`);
      onlyEn.forEach((key) => console.error(`  - ${key}`));
    }
    process.exit(1);
  }

  console.log(`i18n parity OK (${esKeys.length} keys in es.json and en.json).`);

  if (shouldWriteTypes) {
    writeTypes(esKeys);
    console.log('Generated', path.relative(ROOT, TYPES_PATH));
  }
}

main();
